### PR TITLE
Remove audience length check

### PR DESCRIPTION
**Pull request by kukicado**
Fixes https://github.com/square/go-jose/issues/151

### CODE REVIEW

**Comment by mcpherrinm** [comment]
I think this PR should be against `master`, not `v2`.  @csstaub ?

**Comment by mcpherrinm** [comment]
This change LGTM, though there is a test failure.  Possibly the test needs updating (I haven't looked at it).

CLA is signed.

**Comment by kukicado** [comment]
Fixed the tests. Had to remove the tests that checked for aud equality.

**Comment by csstaub** [comment]
LGTM, thank you for your contribution. Would you like me to release a tagged version with this fix?

**Comment by kukicado** [comment]
Thank you for merging this so quickly. I really appreciate it. If you could do a tagged release that would be amazing.

Thanks again!

**Comment by csstaub** [comment]
Tagged as v2.1.2: https://github.com/square/go-jose/releases/tag/v2.1.2 

Thanks to you for finding & fixing the bug!

**Pull request merged**
