### PR TITLE
Add support for *CBC+HS* encryption

### PR DESCRIPTION
**Pull request by connor4312**
This PR adds support A128CBC+HS256, A192CBC+HS384, and A256CBC+HS512 content encryption. This set of encryption algorithms is from an older version of the JOSE RFC but they can still be found in the wild (particularly when compatibility with older systems is required.)

### CODE REVIEW

**Comment by csstaub** [comment]
Hi, thanks for the pull request! I will be able to review this tomorrow. If you haven't already, make sure to sign Square's [Individual Contributor License Agreement][1] (applies to all contributors with commits). I can't accept contributions without the agreement. Thanks!

 [1]: https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1

**Comment by connor4312** [comment]
Hi @csstaub, this contributed code is from Microsoft, rather than an individual. Do you have a corporate CLA and/or an email address for legal contact?

**Comment by csstaub** [comment]
I will look into that, will get back to you.

**Comment by csstaub** [comment]
Hi @connor4312, you can contact me at cs@squareup.com and we'll get this set up.

**Pull request closed without merging**
