### PR TITLE
JWT typed builders and merge support

### PR DESCRIPTION
**Pull request by shaxbee**
Made Builder into interface and create two implementations - signedBuilder and encryptedBuilder.
Removed hack around marshalling/unmarshalling claims.

Still unsure about separate methods for Public and Private claims.

### CODE REVIEW

**Comment by shaxbee** [comment]
Marshal/Unmarshal pair in claims merging should be replaced by function that will use the json tags to Marshal data into map.

**Comment by csstaub** [comment]
Hi @shaxbee, this looks pretty good at first glance. I noticed you tagged this as "WIP" so I haven't taken a deeper look yet. Is there anything else you want to add?

**Comment by shaxbee** [comment]
Hello @csstaub if you're comfortable with API then let's merge it, I'll continue working on test coverage in separate PR.

**Comment by csstaub** [comment]
Looks good -- thanks @shaxbee.

**Comment by shaxbee** [comment]
@ericchiang In case you're using v2 please note that API for JSONWebToken.Claims changed - key parameter is first now, followed by zero or more claims.

**Pull request merged**
