### PR TITLE
Add opaque key encryption and opaque key decryption

### PR DESCRIPTION
**Pull request by garrickb**
Following the existing `OpaqueSigner` and `OpaqueVerifier`, I have added an `OpaqueKeyEncrypter` and `OpaqueKeyDecrypter`. This adds the ability to provide an opaque encrypter and decrypter. The motivation behind this is to support using a KMS to encrypt/decrypt CEKs.

Related issue: #256

### CODE REVIEW

**Comment by garrickb** [comment]
@csstaub any idea why GolangCI can't analyze?

**Comment by csstaub** [comment]
Not sure, but I will take a look. This looks like a good v2 addition btw before I refactor this whole code for v3 to make this type of thing easier.

**Comment by garrickb** [comment]
> Not sure, but I will take a look. This looks like a good v2 addition btw before I refactor this whole code for v3 to make this type of thing easier.

Is there any additional work for me to get this change in v2? Do I need to create a PR on the `v2` branch?

**Comment by csstaub** [comment]
I can merge it into the v2 branch and tag it, just haven't gotten around to looking at this in detail yet.

**Comment by garrickb** [comment]
Do you know when you'd be able to take a look over this, @csstaub ?

**Comment by csstaub** [comment]
I'll work on it this weekend

**Comment by csstaub** [comment]
LGTM, thank you @garrickb. I rebased onto v2 branch in #261. Note for v3 I want to eventually land #248, which should allow for something similar by getting rid of reflection and exposing an interface for decryption/encryption keys.

**Pull request closed without merging**
