### PR TITLE
Add basic support for x5c in JWKs

### PR DESCRIPTION
**Pull request by csstaub**
Add basic support for x5c in JWKs. cc @arekkas

### CODE REVIEW

**Comment by csstaub** [comment]
@arekkas since this is based on your pull request #96, would you mind signing our CLA to confirm that we can use your code?

**Comment by arekkas** [comment]
done

**Comment by arekkas** [comment]
I force-pushed a squashed commit on the closed PR but it looks like closed PRs are not being updated with new pushes. However, I signed the latest commit from the PR https://github.com/square/go-jose/pull/96/commits/7a1e23fe87d7ea2ee4c889be8d070a438d4a254b - hope that's enough.

**Comment by csstaub** [comment]
@arekkas I was referring to our CLA here: https://docs.google.com/a/squareup.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1

**Comment by arekkas** [comment]
Ohhh I'm sorry I thought singing off is enough :) Done!

**Comment by csstaub** [comment]
great 👍  thanks for your contribution!

**Comment by arekkas** [comment]
:open_hands: thanks for your patience :)

**Pull request merged**
