### PR TITLE
Move ed25519

### PR DESCRIPTION
**Pull request by csstaub**
Via #258, and also dropping Go <1.13 support on master (no need to support old versions on v3).

### CODE REVIEW

**Comment by mbyczkowski** [comment]
@csstaub looks like there's an issue with GolangCI running inside the test suite. Given that we now have GolangCI integration for this repo, maybe we should remove it from the .travis.yml file?

**Comment by csstaub** [comment]
Yeah that makes sense

**Comment by mbyczkowski** [comment]
@csstaub I have rebased this PR on master (and added a little note about Go 1.13+ requirement to README). Does this look good to you?

**Comment by mbyczkowski** [comment]
@csstaub ping on this. Also, should we backport this to v2? I think it could be reasonable to require Go 1.13 at some point for v2, just not sure if we want to do that soon.

**Comment by csstaub** [comment]
@mbyczkowski Let's do it. I can't merge myself due to restricted branch, but feel free to land this. Backporting sounds ok too it's been long enough imo.

**Comment by mikekamornikov** [comment]
@mbyczkowski Do you plan to cut `V2` release with this one anytime soon? We have several deps using `gopkg.in/square/go-jose.v2` and issues like this one blocking `go1.13` upgrade:
```
<our package> imports
  github.com/coreos/go-oidc imports
  gopkg.in/square/go-jose.v2 imports
  golang.org/x/crypto/ed25519 imports
  crypto/ed25519: malformed module path "crypto/ed25519": missing dot in first path element
```

**Comment by mbyczkowski** [comment]
@mikekamornikov I'm not sure this is the same issue. Can you file a new issue with some repro steps?

**Comment by mikekamornikov** [comment]
It looks like our issue was caused by calls from env without `GO111MODULE=on`.

**Pull request merged**
