### PR TITLE
add confirmation claim to Claims struct

### PR DESCRIPTION
**Pull request by zamicol**
Idea for #119.

### CODE REVIEW

**Comment by csstaub** [comment]
Is this all that's needed? No validation or anything? Also `interface{}` is not very useful as a type

**Comment by csstaub** [comment]
Just briefly looked at RFC 7800 it looks like the `cnf` claim can contain `jwk` (Section 3.2) for public keys, `jwe` (Section 3.3) for wrapped symmetric keys, `kid` (Section 3.4) for key ids, `jku` (and `kid`) for a URL representation.

Those values should be represented by corresponding structs in the code, and we should have custom `UnmarshalJSON` implementations for them to parse & sanity check them appropriately. For example, when parsing a JWK from a `jwk` field we should ensure that the JWK represents a public key only (and not a private/symmetric key, for example). For for other values. 

Also, I'm not convinced about the utility of `jku`... that's just asking for trouble. I guess we could expose it as a `url.URL` (from net/url) in case anyone wants it, but let's avoid making any network requests in the library itself.

**Comment by shaxbee** [comment]
I'll be able to work on this after v2 release, probably only jwk field will be used. I wonder if the additional registered claims shouldn't have their own structs, instead of adding stuff to existing jwt.Claims.

**Comment by zamicol** [comment]
Sorry for being aloof, I should be able to get back to you tonight.  

Section 6.2 mentions the confirmation methods registry which can be found here: https://www.iana.org/assignments/jwt/jwt.xhtml#confirmation-methods

So only these four: "jwk", "jwe",  "jku", and "kid".

**Pull request closed without merging**
