### PR TITLE
Add support for x5u parameter in jwk

### PR DESCRIPTION
**Pull request by 0x13a**
as discussed here https://github.com/square/go-jose/issues/240

### CODE REVIEW

**Comment by csstaub** [comment]
This won't expose it to callers of the library though, which is probably what you want (the raw representation is private and is only for a pre-parsing step). Let me work on a quick PR to add this, I realized while we're at it we should also add x5t and x5t#S256 probably and validate their values.

**Comment by 0x13a** [comment]
yes thanks. would certificate URI suffice and makes sense? please check commit 
e76ad40

**Comment by 0x13a** [comment]
@csstaub I can also add the thumbprint and the sha256-Thumbprint parameters as well. do you want to do some sort of validation during unmarshalling?

**Comment by csstaub** [comment]
Yes, I have some code changes I'm working on. Hang tight.

**Comment by csstaub** [comment]
See #242 for a proposed implementation with x5u/x5t support and additional validation checks.

**Comment by 0x13a** [comment]
brilliant, thanks

**Pull request closed without merging**
