### PR TITLE
Regenerate X.509 cert with SAN extension

### LINKED ISSUE #330: TestJWSWithCertificateChain failed with go1.15
```
=== RUN   TestJWSWithCertificateChain
    jws_test.go:615: failed to verify certificate chain for test case 0: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
--- FAIL: TestJWSWithCertificateChain (0.00s)
```

### PR DESCRIPTION
**Pull request by pippo**
The certificate for CN=TrustedSigner has been regenerated with SAN extension.
Due to missing keys, certs for CN=TrustedCA & CN=IntermediateCA have been regenerated as well.

Resolves #330.

### CODE REVIEW

**Review by csstaub — APPROVED** [review]

**Comment by csstaub** [comment]
Thanks @pippo! We should merge this into the v2 branch and then I can tag a release with it

**Comment by pippo** [comment]
no problem, @csstaub.
As for the wrong branch, apologies, didn't know that. Shall I rebase against v2 and create a new PR?

**Comment by csstaub** [comment]
Yes that'd be great thank you @pippo

**Comment by pippo** [comment]
OK. PR #332 created.

**Comment by pippo** [comment]
@csstaub shall I close this PR?

**Comment by mbyczkowski** [comment]
Yup, I just merged #332. Thanks!

**Pull request closed without merging**
