### PR TITLE
Regenerate X.509 cert with SAN extension (v2)

### LINKED ISSUE #330: TestJWSWithCertificateChain failed with go1.15
```
=== RUN   TestJWSWithCertificateChain
    jws_test.go:615: failed to verify certificate chain for test case 0: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
--- FAIL: TestJWSWithCertificateChain (0.00s)
```

### PR DESCRIPTION
**Pull request by pippo**
The certificate for CN=TrustedSigner has been regenerated with SAN extension.
Due to missing keys, certs for CN=TrustedCA & CN=IntermediateCA have been regenerated as well.

Resolves #330.

### CODE REVIEW

**Review by csstaub — APPROVED** [review]

**Comment by csstaub** [comment]
Ah, looks like I build error in CI. We'll have to bump Go version in the travis-ci config on v2 (https://github.com/square/go-jose/blob/master/.travis.yml)

**Comment by csstaub** [comment]
I should have some time to work on this later tonight to get it merged

**Comment by pippo** [comment]
ok, thanks. Let me know if I can do anything else here.

**Comment by csstaub** [comment]
PR: https://github.com/square/go-jose/pull/333

**Comment by mbyczkowski** [comment]
@pippo can you rebase your PR on latest v2 branch (I merged #333), I think it should pass the CI now.

**Comment by pippo** [comment]
Sure. Will do.

**Comment by pippo** [comment]
There you go @mbyczkowski. The build passed indeed. 👍

**Comment by pippo** [comment]
Nice. I'd appreciate if you added "hacktoberfest-accepted" label to this PR. Thanks.

**Comment by csstaub** [comment]
Thanks everyone! We appreciate your contributions

**Pull request merged**
